<!-- Copyright (c) 2026 xregistry-dotnet contributors. -->
<!-- SPDX-License-Identifier: MIT -->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks />
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\XRegistry.Server\XRegistry.Server.csproj" />
    <Compile Include="..\..\samples\Shared\RegistrySample*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
