# Copyright (c) 2026 xregistry-dotnet contributors.
# SPDX-License-Identifier: MIT

"""Repository-level documentation, restore and license policy checks."""

from __future__ import annotations

import os
import re
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[2]
PROTECTED_DOCS = (
    Path("tests/Conformance/Sources"),
    Path("tests/Conformance/Corrections"),
)
PRUNED = {".git", "artifacts", "bin", "obj", ".vs", ".idea", "__pycache__", ".pytest_cache"}


def repository_files() -> list[Path]:
    result = []
    for directory, names, files in os.walk(ROOT, followlinks=False):
        names[:] = [
            name for name in names
            if name not in PRUNED and not (Path(directory) / name).is_symlink()
        ]
        result.extend(Path(directory) / name for name in files)
    return result


def owned_markdown() -> set[Path]:
    result: set[Path] = set()
    for path in repository_files():
        if path.suffix.lower() != ".md":
            continue
        relative = path.relative_to(ROOT)
        if any(item == relative or item in relative.parents for item in PROTECTED_DOCS):
            continue
        result.add(relative)
    return result


class DocumentationPolicyTests(unittest.TestCase):
    def test_root_readme_uses_samples_build_and_documentation_order(self) -> None:
        text = (ROOT / "README.md").read_text(encoding="utf-8")
        samples = text.index("## 🧪 Samples")
        build = text.index("## 🛠️ Build")
        documentation = text.index("## 📚 Documentation")
        self.assertLess(samples, build)
        self.assertLess(build, documentation)
        self.assertNotIn("Implemented, not release-qualified", text)
        self.assertNotIn("Existing OPC UA integration is informative consumer input", text)
        for path in (
            "samples/XRegistry.FileServer/README.md",
            "samples/XRegistry.FederationBridge/README.md",
            "samples/XRegistry.Client/README.md",
        ):
            self.assertIn(path, text.replace("\\", "/"))
        self.assertIn("(docs/README.md)", text.replace("\\", "/"))
        self.assertNotIn("packages.lock.json", text)
        self.assertNotIn("--locked-mode", text)
        self.assertNotIn("-UpdateLocks", text)

    def test_docs_index_links_every_owned_markdown_document(self) -> None:
        index = ROOT / "docs" / "README.md"
        self.assertTrue(index.is_file())
        text = index.read_text(encoding="utf-8")
        links = {
            target.split("#", 1)[0]
            for target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text)
            if "://" not in target and not target.startswith("#")
        }
        resolved = {
            (index.parent / target.replace("%20", " ")).resolve().relative_to(ROOT.resolve())
            for target in links
        }
        expected = owned_markdown() - {Path("docs/README.md")}
        self.assertEqual(expected, resolved)
        self.assertIn(Path("docs/roadmap.md"), expected)
        self.assertIn(Path("docs/changelog.md"), expected)
        self.assertIn(Path("eng/specification/README.md"), expected)

    def test_future_and_history_headings_are_confined_to_designated_documents(self) -> None:
        forbidden = re.compile(
            r"(?im)^#{1,6}\s+(?:.*\bremaining (?:work|qualification|coverage|profile)\b|"
            r".*\bfuture (?:work|features?)\b|.*\bnext steps?\b|historical checkpoints?)\s*$"
        )
        offenders = {}
        for relative in owned_markdown():
            if relative in {Path("docs/roadmap.md"), Path("docs/changelog.md")}:
                continue
            matches = forbidden.findall((ROOT / relative).read_text(encoding="utf-8"))
            if matches:
                offenders[str(relative)] = matches
        self.assertEqual({}, offenders)
        roadmap = (ROOT / "docs" / "roadmap.md").read_text(encoding="utf-8")
        changelog = (ROOT / "docs" / "changelog.md").read_text(encoding="utf-8")
        self.assertIn("qualification", roadmap.lower())
        self.assertIn("native aot", roadmap.lower())
        self.assertIn("SPEC-001", changelog)
        self.assertIn("SPEC-020", changelog)

    def test_current_limits_and_release_safeguards_remain_in_current_guides(self) -> None:
        security = (ROOT / "docs" / "security.md").read_text(encoding="utf-8").lower()
        releasing = (ROOT / "docs" / "releasing.md").read_text(encoding="utf-8").lower()
        conformance = (ROOT / "docs" / "conformance.md").read_text(encoding="utf-8")
        self.assertIn("immutable", security)
        self.assertIn("hash-verified", security)
        self.assertIn("release", releasing)
        self.assertIn("qualification", releasing)
        self.assertIn("Generated by `python eng\\specification\\manage.py generate`.", conformance)
        self.assertNotIn("**Not release-qualified.**", conformance)
        self.assertIn("not evidence that the client/server implements them", conformance.lower())
        self.assertIn("| Family | Blocks | Reviewed | Qualified |", conformance)


class RestoreAndLicensePolicyTests(unittest.TestCase):
    def test_repository_has_no_nuget_lockfiles_or_locked_restore_machinery(self) -> None:
        lockfiles = [
            path.relative_to(ROOT)
            for path in repository_files()
            if path.name.endswith("packages.lock.json")
        ]
        self.assertEqual([], lockfiles)
        files = (
            ROOT / "Directory.Build.targets",
            ROOT / "eng" / "build.ps1",
            ROOT / "eng" / "test-embedding-packages.ps1",
            ROOT / "eng" / "test-git-interop.ps1",
            ROOT / ".github" / "workflows" / "aot.yml",
            ROOT / "eng" / "containers" / "model-package-smoke.Dockerfile",
        )
        forbidden = ("--locked-mode", "RestoreLockedMode", "NuGetLockFilePath", "UpdateLocks")
        for path in files:
            text = path.read_text(encoding="utf-8")
            for value in forbidden:
                self.assertNotIn(value, text, f"{value} remains in {path.relative_to(ROOT)}")
        props = (ROOT / "Directory.Build.props").read_text(encoding="utf-8")
        self.assertIn("<RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>", props)
        ignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
        self.assertIn("**/packages.lock.json", ignore)
        self.assertIn("**/*.packages.lock.json", ignore)

    def test_central_versions_audit_source_mapping_and_provenance_locks_remain(self) -> None:
        packages = (ROOT / "Directory.Packages.props").read_text(encoding="utf-8")
        props = (ROOT / "Directory.Build.props").read_text(encoding="utf-8")
        nuget = (ROOT / "NuGet.config").read_text(encoding="utf-8")
        self.assertIn("<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>", packages)
        self.assertIn("<NuGetAudit>true</NuGetAudit>", props)
        self.assertIn("<NuGetAuditMode>all</NuGetAuditMode>", props)
        self.assertIn("<packageSourceMapping>", nuget)
        self.assertTrue((ROOT / "eng" / "requirements-oracles.lock").is_file())
        self.assertTrue((ROOT / "eng" / "specification-lock.json").is_file())

    def test_captured_specification_requirements_are_not_installed_by_repository_workflows(self) -> None:
        captured = ROOT / "tests" / "Conformance" / "Sources" / "tools" / "requirements.txt"
        active = ROOT / "eng" / "requirements-oracles.lock"
        self.assertIn("aiohttp==3.11.12", captured.read_text(encoding="utf-8"))
        self.assertNotIn("aiohttp", active.read_text(encoding="utf-8"))

        workflow_text = "\n".join(
            path.read_text(encoding="utf-8")
            for path in (ROOT / ".github" / "workflows").glob("*.yml")
        )
        self.assertIn("eng/requirements-oracles.lock", workflow_text)
        self.assertNotIn("tests/Conformance/Sources/tools/requirements.txt", workflow_text)
        self.assertNotIn("tools/requirements.txt", workflow_text)

        security = (ROOT / "docs" / "security.md").read_text(encoding="utf-8")
        self.assertIn("not an installation source", security)
        self.assertIn("active lock does not include `aiohttp`", security)

    def test_root_license_names_contributors_and_retains_mit_terms(self) -> None:
        license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
        self.assertIn("Copyright (c) 2026 xregistry-dotnet contributors", license_text)
        self.assertIn("Permission is hereby granted, free of charge", license_text)
        self.assertIn('THE SOFTWARE IS PROVIDED "AS IS"', license_text)
        self.assertIn("LIABILITY, WHETHER IN AN ACTION OF CONTRACT", license_text)


if __name__ == "__main__":
    unittest.main()
