<!-- Copyright (c) 2026 xregistry-dotnet contributors. -->
<!-- SPDX-License-Identifier: MIT -->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>XRegistry.Storage.File</PackageId>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XRegistry.Server\XRegistry.Server.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
