<!-- Copyright (c) 2026 xregistry-dotnet contributors. -->
<!-- SPDX-License-Identifier: MIT -->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>XRegistry.Federation</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XRegistry\XRegistry.csproj" />
    <ProjectReference Include="..\XRegistry.Client\XRegistry.Client.csproj" />
    <ProjectReference Include="..\XRegistry.Models\XRegistry.Models.csproj" />
  </ItemGroup>
</Project>
